### ISSUE TITLE
SMTP Gmail configuration does not sem to work

### ISSUE THREAD

**Issue by th0r88** [shukriadams/arewedown#11]
Hi,

thanks for your hard work! I just set it up with docker-compose and created settings.yml.

It doesn't seem when a service is down (I only use URL: tag at the moment) that I get an email.

My conf:

```
transmissions:
    smtp:
        enabled: true
        server: smtp.gmail.com
        port: 465
        secure: true
        user: user@gmail.com
        pass: GoogleAppPassword
        from: user@gmail.com
```

Any tips?

**Comment by shukriadams** [comment]
I also had problems getting this to work first time round with my own gmail account, and it came down to auth restrictions with gmail itself. Can you see what's in the startup log for AWD? If you're running the docker version try `docker logs arewedown`, the smtp transport will attempt to authenticate on app start, hopefully that will give you a clue as to what is going wrong. Paste your log error if you get one.

**Comment by sstoefe** [comment]
It looks like the documentation is outdated. It's transports instead of transmissions.
I had the same issue.

My now working settings.yml looks like this:
```
transports:
  smtp:
    enabled: true
    server: smtp.gmail.com
    port: 465
    secure: true
    user: "{{env.GOOGLE_USER}}"
    pass: "{{env.GOOGLE_PASSWORD}}"
    from: user@gmail.com

recipients:
  user:
    enabled: true
    smtp: user@gmail.com

watchers:
    ....
```
