### ISSUE TITLE
Docker ARM image not working on QNAP ARM Cortex-A15

### ISSUE THREAD

**Issue by cubagithub** [shukriadams/arewedown#15]
Followed setup steps in readme.

```bash
[admin@QNAP ~]# docker-compose logs
Attaching to AreWeDown, Portainer
AreWeDown    | terminate called after throwing an instance of 'std::length_error'
AreWeDown    |   what():  basic_string::_M_replace_aux
AreWeDown    | Aborted
AreWeDown    | terminate called after throwing an instance of 'std::length_error'
AreWeDown    |   what():  basic_string::_M_replace_aux
AreWeDown    | Aborted
AreWeDown    | terminate called after throwing an instance of 'std::length_error'
AreWeDown    |   what():  basic_string::_M_replace_aux
AreWeDown    | Aborted
AreWeDown    | terminate called after throwing an instance of 'std::length_error'
AreWeDown    |   what():  basic_string::_M_replace_aux
AreWeDown    | Aborted
AreWeDown    | terminate called after throwing an instance of 'std::length_error'
AreWeDown    |   what():  basic_string::_M_replace_aux
AreWeDown    | Aborted
AreWeDown    | terminate called after throwing an instance of 'std::length_error'
AreWeDown    |   what():  basic_string::_M_replace_aux
AreWeDown    | Aborted
AreWeDown    | terminate called after throwing an instance of 'std::length_error'
AreWeDown    |   what():  basic_string::_M_replace_aux
AreWeDown    | Aborted
```

OS info:
```bash
[~] # uname -a
Linux QNAP 4.2.8 #2 SMP Thu Jul 4 05:26:06 CST 2019 armv7l unknown
```

Docker compose file:
```yaml
version: "3"
services:
  portainer:
    container_name: Portainer
    image: portainer/portainer
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /share/Docker/portainer:/data

  arewedown:
    image: shukriadams/arewedown:0.2.0-arm
    container_name: AreWeDown
    restart: unless-stopped
    volumes:
    - /share/Docker/arewedown/config:/etc/arewedown/config
    - /share/Docker/arewedown/logs:/etc/arewedown/logs/:rw
    # - ./scripts:/etc/arewedown/custom-tests # optional, see "custom tests" section of documentation
    ports:
      - "3000:3000"
```

Permissions on logs path:
```bash
[admin@QNAP ~]# ls -la /share/Docker/arewedown/logs
drwxr-xr-x    2 1000     administ        40 May 20 22:32 ./
drwxr-xr-x    4 admin    administ        80 May 20 22:32 ../
```

Settings file (empty as per readme):
```bash
[admin@QNAP ~]# ls -la /share/Docker/arewedown/config/
drwxr-xr-x    2 admin    administ        60 May 20 22:37 ./
drwxr-xr-x    4 admin    administ        80 May 20 22:32 ../
-rw-r--r--    1 admin    administ         0 May 20 22:37 settings.yml
```
