### ISSUE TITLE
Custom tests

### ISSUE THREAD

**Issue by lfoppiano** [shukriadams/arewedown#23]
Hi, I'm trying to use custom tests to check whether a service is running. 

I tried by probing the ports but it was not working (probably they are not using tcp), so I tried this: 

```
    mongo:
        cmd: pgrep mongod | grep -c -e '[0-9]\+' | grep "1"

    mysql:
        cmd: pgrep mysqld_safe | grep -q -e '[0-9]\+'

```

but for both of them I get error 1. Any clue?
